### PR TITLE
turns out we didn't want to strip the namespaces out here!

### PR DESCRIPTION
**Pull request by ddellacosta**

### CODE REVIEW

**Comment by cap10morgan** [comment]
Oh! We already had some namespace mojo going eh? Sorry for breaking it. Are there any tests we could add that would have failed on this change?

**Comment by cap10morgan** [comment]
@ddellacosta Saw this got merged, so I wanted to make sure you saw my question above.

**Comment by ddellacosta** [comment]
@cap10morgan yeah sorry, was talking with Ben this whole time but I saw your message. Basically I just missed the fact that the reporting code was working in the fashion we want already, and stripping namespaces actually breaks that.  I'll take a look and see if I can't add some tests to try to detect this but I wanted to get a fix up ASAP because the admin console was broken.

**Comment by cap10morgan** [comment]
@ddellacosta Cool. Yeah, I'm 👍 on getting the fix out quickly. Thanks!

**Pull request merged**
