### PR TITLE
Replace either w/ conditional in schema

### PR DESCRIPTION
**Pull request by cap10morgan**
`either` was deprecated in the schema library and the better error messages alone make `conditional` a
huge win over it anyway.

I used `conditional` to help debug a problem I was seeing in krakenstein and it was very helpful. So I figured I put it up in a PR for others to benefit from too.

### CODE REVIEW

**Comment by sduckett** [comment]
@cap10morgan Do you have an example of how are the error messages better?

**Comment by cap10morgan** [comment]
Not handy, but basically the difference is `either` tells you *that* it didn't match but `conditional` tells you *why* (like most validation errors do in schema).

**Comment by sduckett** [comment]
LGTM

**Comment by sduckett** [comment]
Let's merge this one, @cap10morgan 👍

**Pull request merged**
