### PR TITLE
Add formatted timestamps to export

### PR DESCRIPTION
**Pull request by tank157**
[Pivotal Card](https://www.pivotaltracker.com/story/show/127932173)

Assigning to @7maples

### CODE REVIEW

**Comment by 7maples** [comment]
I would love to generate an export to test this, but cannot find any documentation in the readme or torchpad. Do you have some instructions I could try, and then create documentation out of?

**Comment by tank157** [comment]
I do not. I admittedly have never done that myself, despite adding a few
fields to the exports. You'll need to check with Daniel or Dave to get
those instructions.

**Comment by tank157** [comment]
But what i have done is added a println of the pr-str'd users to the export
test and looked at it that way in the REPL output.

**Comment by 7maples** [comment]
LGTM

**Comment by tank157** [comment]
The changes to export will likely clobber this work as it exists, so since it's pretty small, will re-implement over there.

**Pull request closed without merging**
